added httpMethod in perform action parameter and default to http.Get
jliliamen/WordPressLicenseManagerNETClient pull request #5
Opened 2021-04-05 19:02 UTC by xavave

2021-04-05 23:25 UTC, jliliamen approved these changes
Should be good... nothing to see here

2021-04-05 23:29 UTC, jliliamen requested changes

2021-04-05 23:29 UTC, jliliamen commented on src/LicenseManager.cs
> +            {
@xavave  I think you need to inject httpMethod synchronous method

2021-04-05 23:29 UTC, jliliamen commented on Tests/WPLMNETClient.NetFramework.Tests/Tests.cs
We should prolly add a little  comment to the user the configuration and license object are specific to their website

2021-04-06 07:22 UTC, xavave commented
I'm not sure to fully understand your change request: anyway, I've modified configuration parameters (which were specific to your debugging server) 
I've also I've found and fixed another  issue:  the 3 dates sent to server (date_created,date_renewed,date_expiry) were sent empty, because server is waiting for this date type: yyyy-MM-dd so I've parsed these datetimes with ToString("yyyy-MM-dd") and, now the dates are properly sent to the server.

the first issue was not related to synchronous or asynchronous method (I was already using synchronous method), but due to the fact that my client App (a WPF app) is not located on the wordpress server (which is on my synology NAS) so I guess that when you want to POST method from an external location to the wordpress server, wordpress POST client request needs to be authentified , whereas with GET method , no need to authenticate with a wordpress account /token before sending the request

2021-04-06 23:47 UTC, jliliamen commented
I'm talking about this : 
![image](https://user-images.githubusercontent.com/16106587/113791059-a38dcd80-96f7-11eb-8885-e692d26878ef.png)
You forget to pass the optional parameter... 

I'll fix that myself no problem. Thanks for your commits! Merci beaucoup!

2021-04-06 23:47 UTC, merged